services:
  constructora:
    container_name: constructora
    build:
      context: ./docker/php
      dockerfile: Dockerfile  # Si usas un Dockerfile personalizado
    volumes:
      - ./:/var/www/html  # Mapea todo el directorio del proyecto al contenedor
    depends_on:
      - db
    networks:
      - constructora_network
    environment:
      - SYMFONY_ENV=dev
      - APP_SECRET=your-app-secret

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - constructora
    volumes:
      - ./:/var/www/html  # Mapea todo el directorio del proyecto al contenedor
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Archivos de configuración de nginx
    networks:
      - constructora_network
    ports:
      - "8082:80"

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: administrador
      MYSQL_DATABASE: constructora
      MYSQL_USER: administrador
      MYSQL_PASSWORD: administrador
    volumes:
      - db_data:/var/lib/mysql  # Persistencia de datos de la base de datos
    networks:
      - constructora_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: administrador
    ports:
      - "8083:80"
    networks:
      - constructora_network

volumes:
  db_data:  # Volumen persistente para la base de datos MySQL

networks:
  constructora_network:
    driver: bridge