project:
  path: /project
  defaults: { _controller: App\Controller\Admin\ProjectController::index }

listarProjectAdmin:
  path: /project/listarProject
  defaults: { _controller: App\Controller\Admin\ProjectController::listar, _format: json }

eliminarProjectAdmin:
  path: /project/eliminarProject
  defaults: { _controller: App\Controller\Admin\ProjectController::eliminar, _format: json }

eliminarProjectsAdmin:
  path: /project/eliminarProjects
  defaults: { _controller: App\Controller\Admin\ProjectController::eliminarProjects, _format: json }

salvarProjectAdmin:
  path: /project/salvarProject
  defaults: { _controller: App\Controller\Admin\ProjectController::salvar, _format: json }

cargarDatosProjectAdmin:
  path: /project/cargarDatos
  defaults: { _controller: App\Controller\Admin\ProjectController::cargarDatos, _format: json }

listarProjectsOrdenadosAdmin:
  path: /project/listarOrdenados
  defaults: { _controller: App\Controller\Admin\ProjectController::listarOrdenados, _format: json }

#items details
listarItemDetailsProjectAdmin:
  path: /project/listarItemDetails
  defaults: { _controller: App\Controller\Admin\ProjectController::listarItemDetails, _format: json }

salvarItemDetailsProjectAdmin:
  path: /project/salvarItemDetails
  defaults: { _controller: App\Controller\Admin\ProjectController::salvarItemDetails, _format: json }

cargarDatosItemDetailsProjectAdmin:
  path: /project/cargarDatosItemDetails
  defaults: { _controller: App\Controller\Admin\ProjectController::cargarDatosItemDetails, _format: json }

eliminarItemDetailsProjectAdmin:
  path: /project/eliminarItemDetails
  defaults: { _controller: App\Controller\Admin\ProjectController::eliminarItemDetails, _format: json }

listarItemDetailsParaInvoiceProjectAdmin:
  path: /project/listarItemDetailsParaInvoice
  defaults: { _controller: App\Controller\Admin\ProjectController::listarItemDetailsParaInvoice, _format: json }